### ISSUE TITLE
#RuntimeError

### ISSUE THREAD

**Issue by Mojgan-arch** [muxamilian/city-gan#2]
The argparse is giving me this error 
usage: gan.py [-h] --dataset DATASET --dataroot DATAROOT [--workers WORKERS]
              [--batchSize BATCHSIZE] [--imageSize IMAGESIZE] [--hack]
              [--classifyGenerated] [--nonConditional] [--cropSize CROPSIZE]
              [--nz NZ] [--ngf NGF] [--ndf NDF] [--niter NITER] [--lr LR]
              [--beta1 BETA1] [--cuda] [--netG NETG] [--netD NETD]
              [--outf OUTF] [--function FUNCTION] [--arg ARG]
              [--manualSeed MANUALSEED] [--numSamples NUMSAMPLES]
              [--numClasses NUMCLASSES] [--maxSamples MAXSAMPLES]
gan.py: error: the following arguments are required: --dataset, --dataroot

I think the source of the error is the following line. Could you help me on adding this attribute without any problem?

parser.add_argument('--dataset', required=True, help='cifar10 | lsun | mnist | imagenet | folder | lfw | fake')
parser.add_argument('--dataroot', required=True, help='path to dataset')

**Comment by dcferreira** [comment]
Hi,

You need to pass the `--dataset` and `--dataroot` arguments to the command line.
For example: `python gan.py --dataset cifar10 --dataroot /path/to/cifar10`.
